### ISSUE TITLE
Picture Alignment

### ISSUE THREAD

**Issue by yejonlhee** [UBC-iGEM/simplysynbio#23]
Hello! To be nit picky, the photo and the words beside them on the main page don't exactly line up (at least on my screen). Could we top justify the words to the picture? 

<img width="960" alt="image" src="https://github.com/UBC-iGEM/simplysynbio/assets/151305749/839bdb76-471f-4503-be4e-3df40cf2b1a6">

**Comment by lhao03** [comment]
![image](https://github.com/UBC-iGEM/simplysynbio/assets/55033656/0a3b2a12-0047-467f-9a11-a4cd8e528224)

does this look alright?

**Comment by yejonlhee** [comment]
Yes! Thank you!
