### ISSUE TITLE
Picture not displaying on main page 

### ISSUE THREAD

**Issue by yejonlhee** [UBC-iGEM/simplysynbio#32]
Hi! For @char63's simplysynbio post, the picture display is not available on the main landing page. When I look at Charlotte's github page, everything looks good and similar to the other posts. Do you know what the problem could be? 
<img width="857" alt="image" src="https://github.com/UBC-iGEM/simplysynbio/assets/151305749/66b6e6ab-4b5c-4cf3-b2e1-f0f6078809c3">

**Comment by lhao03** [comment]
she didn't add this property 
<img width="341" alt="image" src="https://github.com/UBC-iGEM/simplysynbio/assets/55033656/cb86e5dd-2c76-4f0c-af65-27e02d84c817">
