### ISSUE TITLE
create "how long to read" for each post

### ISSUE THREAD

**Issue by yejonlhee** [UBC-iGEM/simplysynbio#6]
based on how many words are in the blog post, add a field to the blog post template that displays how long a blog post takes to read. start with getting the number of words from a blog post

**Comment by lhao03** [comment]
Hi, any progress on this issue?

**Comment by mattmatt777** [comment]
I've tried a few things but still learning. I found a plug-in that might be helpful but i'm not familiar with implementing plug-ins. 
 I'm also looking for a word count function if there is one
 
 Plug-in: (https://www.gatsbyjs.com/plugins/gatsby-read-time-estimate/#gatsby-remark-read-time-estimate)
