### ISSUE TITLE
add author field

### ISSUE THREAD

**Issue by yejonlhee** [UBC-iGEM/simplysynbio#7]
allow for an "author" field.
![image](https://github.com/UBC-iGEM/simplysynbio/assets/55033656/0907e472-8a66-4696-ae67-8bd6ed9cb8bf)

**Comment by ar4047** [comment]
I can take this one, I don't seem to have permission to assign myself though

**Comment by lhao03** [comment]
Hi, any progress on this issue?

**Comment by ar4047** [comment]
Hi, yes it just took me some time to figure out where I was supposed to add these components, but I should be able to get this done soon. Sorry for the delay!

**Comment by lhao03** [comment]
No worries, just checking in! Thanks for working on the issue!
